### PR TITLE
deps(updatecli): bump all policies

### PR DESCRIPTION
**Pull request by obltmachine**
<Actions>
    <action id="dde5b55d706dc9613a272894a740a95715a01496ce03fb4e71dbfdaaf38f2aaa">
        <h3>deps(updatecli/policy): bump &#34;ghcr.io/elastic/oblt-updatecli-policies/oblt-cli/version&#34; Updatecli policy version</h3>
        <details id="db669af634b75c7f298400f3b6c2aa8ba54998bac83e23d10ab4eaadc4b50ccf">
            <summary>deps(updatecli/policy): bump &#34;ghcr.io/elastic/oblt-updatecli-policies/oblt-cli/version&#34; Updatecli version policy</summary>
            <p>change detected:&#xA;&#x9;* key &#34;$.policies[0].policy&#34; updated from &#34;ghcr.io/elastic/oblt-updatecli-policies/oblt-cli/version:0.0.2@sha256:dd79537aa64a28c57da351182a70a2a798e9b6c5eb55c243fdbd4f5bffe5133d&#34; to &#34;ghcr.io/elastic/oblt-updatecli-policies/oblt-cli/version:0.0.3@sha256:8b996fc5e4351610117ad87e0cc74f562c8228c967a5dde0ed2f9c28f1935c3c&#34;, in file &#34;/tmp/updatecli/github/elastic/oblt-actions/update-compose.yaml&#34;</p>
        </details>
        <a href="https://github.com/elastic/oblt-actions/actions/runs/9870587550">GitHub Action workflow link</a>
    </action>
</Actions>

---

<table>
  <tr>
    <td width="77">
      Updatecli logo
    </td>
    <td>
      <p>
        Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>
      </p>
      <details><summary>Options:</summary>
        <br />
        <p>Most of Updatecli configuration is done via <a href="https://www.updatecli.io/docs/prologue/quick-start/">its manifest(s)</a>.</p>
        <ul>
          <li>If you close this pull request, Updatecli will automatically reopen it, the next time it runs.</li>
          <li>If you close this pull request and delete the base branch, Updatecli will automatically recreate it, erasing all previous commits made.</li>
        </ul>
        <p>
          Feel free to report any issues at <a href="https://github.com/updatecli/updatecli/issues">github.com/updatecli/updatecli</a>.<br />
          If you find this tool useful, do not hesitate to star <a href="https://github.com/updatecli/updatecli/stargazers">our GitHub repository</a> as a sign of appreciation, and/or to tell us directly on our <a href="https://matrix.to/#/#Updatecli_community:gitter.im">chat</a>!
        </p>
      </details>
    </td>
  </tr>
</table>

### CODE REVIEW

**Review by v1v — APPROVED** [review]
🤟

**Comment by reakaleek** [comment]
Oh, the commit is not signed. 😅

**Comment by reakaleek** [comment]
@v1v I see, you already created a PR for that :D https://github.com/updatecli/policies/pull/28

**Comment by reakaleek** [comment]
I checkout the branch locally and ran

```
git commit --amend # without any changes
git push -f
```

**Pull request merged**
