### PR TITLE
oblt-cli/setup: Pin oblt-cli version

### PR DESCRIPTION
**Pull request by v1v**
this should help with ensuring no breaking changes can affect our consumers

There is a follow-up to bump the version with `updatecli`

### CODE REVIEW

**Comment by v1v** [comment]
@reakaleek , I guess, the tests should not run for the forked repository

**Comment by reakaleek** [comment]
> @reakaleek , I guess, the tests should not run for the forked repository

Yup.. changing the trigger to `push` on any branch should fix it.

**Comment by v1v** [comment]
> Yup.. changing the trigger to push on any branch should fix it.

See https://github.com/elastic/oblt-actions/pull/54/commits/dea394eff248e6c88fc5dc4a7fbb7f1110738350

but the `test` check is mandatory, how do we fix it?

**Comment by reakaleek** [comment]
Ah, and you need to update https://github.com/elastic/oblt-actions/blob/main/.github/workflows/no-test.yml

**Review by reakaleek — APPROVED** [review]

**Pull request merged**
